### ISSUE TITLE
Adding bintray repo

### ISSUE THREAD

**Issue by dstroyrofworlds** [hmrc/sbt-git-stamp#5]
Not clear on how to add:

Maybe add this:

resolvers ++= Seq(
  Resolver.url(
    "bintray-hmrc-sbt-plugin-releases",
    url("http://dl.bintray.com/hmrc/sbt-plugin-releases"))(
      Resolver.ivyStylePatterns)
)

or publish it Maven style so Resolvers.bintray will work

**Comment by duncancrawford** [comment]
Yes you need to add the following to your project/plugins.sbt:

```scala
resolvers += Resolver.url("hmrc-sbt-plugin-releases",
  url("https://dl.bintray.com/hmrc/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
```

I will update the README to reflect this
