### ISSUE TITLE
Support sbt 1.0.

### ISSUE THREAD

**Issue by sakoht** [hmrc/sbt-git-stamp#9]
I'm using this, and we are upgrading to sbt 1.0.  It seems to fail.

Curious if this project is maintained.  And if not if anyone has a fork?

**Comment by pellekrogholt** [comment]
Well there is a PR for support of sbt 1.1.0 and cross compilation: https://github.com/hmrc/sbt-git-stamp/pull/10

**Comment by bennetimo** [comment]
This is now cross-build for sbt `1.3.4` as of version `6.0.0`
